import os
import sys
import json
import argparse
from typing import Dict

from logger.logger import getLogger
import utils.util as util
import utils.catalog_util as catalog_util
import constants.constants as CONSTANTS

LOGGER = getLogger('processor')


class fbc_processor:
    """
    FBC processor that prepares an OLM catalog for a given RHOAI release. For each invocation it:
      1. Generates catalog_build_args (KEY=VALUE git metadata for Dockerfile build args)
      2. Patches the input catalog with:
         - The new bundle from the single-bundle catalog (SBC)
         - Package/channel updates from catalog-patch.yaml
      3. Processes the Tekton push pipeline (CEL expression enabled/disabled)
      4. Writes all output files

    Inputs:
      - PCC catalog (e.g. main/pcc/catalog-v4.19.yaml) or output from a previous pass
      - Single-bundle catalog generated by opm (contains one olm.bundle document)
      - catalog-patch.yaml (channel entries, package defaults, skipRanges)
      - build-config.yaml (image registry/repo replacement mappings)
      - Push pipeline YAML (Tekton PipelineRun with CEL trigger expression)
      - Git metadata (bundle_git_url, bundle_git_commit of the bundle image)

    Outputs:
      - Patched catalog.yaml
      - catalog_build_args.map
      - Push pipeline YAML
    """

    def __init__(self, rhoai_version: str, build_type: str,
                 build_config_path: str,
                 patch_yaml_path: str,
                 single_bundle_catalog_path: str,
                 input_catalog_path: str,
                 output_catalog_path: str,
                 bundle_git_url: str,
                 bundle_git_commit: str,
                 catalog_build_args_file_path: str,
                 push_pipeline_yaml_path: str,
                 push_pipeline_operation: str,
                 purge_bundles: str = ''):
        LOGGER.info("=============================================================================")
        LOGGER.info("Initializing FBC Processor")
        LOGGER.info("=============================================================================")

        self.rhoai_version = rhoai_version
        self.build_type = build_type
        self.build_config_path = build_config_path
        self.patch_yaml_path = patch_yaml_path
        self.single_bundle_catalog_path = single_bundle_catalog_path
        self.input_catalog_path = input_catalog_path
        self.output_catalog_path = output_catalog_path
        self.bundle_git_url = bundle_git_url
        self.bundle_git_commit = bundle_git_commit
        self.catalog_build_args_file_path = catalog_build_args_file_path
        self.push_pipeline_yaml_path = push_pipeline_yaml_path
        self.push_pipeline_operation = push_pipeline_operation
        self.purge_bundles = purge_bundles

        # e.g. "quay.io/rhoai/odh-operator-bundle" -> component_name="odh-operator-bundle"
        parsed = util.parse_image_value(CONSTANTS.OPERATOR_BUNDLE_IMAGE)
        self.bundle_component_name = parsed['component_name']

        LOGGER.info(f"rhoai_version: {self.rhoai_version}")
        LOGGER.info(f"build_type: {self.build_type}")
        LOGGER.info(f"build_config_path: {self.build_config_path}")
        LOGGER.info(f"patch_yaml_path: {self.patch_yaml_path}")
        LOGGER.info(f"single_bundle_catalog_path: {self.single_bundle_catalog_path}")
        LOGGER.info(f"input_catalog_path: {self.input_catalog_path}")
        LOGGER.info(f"output_catalog_path: {self.output_catalog_path}")
        LOGGER.info(f"git_url: {self.bundle_git_url}")
        LOGGER.info(f"git_commit: {self.bundle_git_commit}")
        LOGGER.info(f"catalog_build_args_file_path: {self.catalog_build_args_file_path}")
        LOGGER.info(f"push_pipeline_yaml_path: {self.push_pipeline_yaml_path}")
        LOGGER.info(f"push_pipeline_operation: {self.push_pipeline_operation}")
        LOGGER.info(f"purge_bundles: {self.purge_bundles or '(none)'}")

        LOGGER.info("")
        LOGGER.info("Loading yaml files...")

        self.build_config = util.load_yaml_file(self.build_config_path, parser='pyyaml')
        self.patch_dict = util.load_yaml_file(self.patch_yaml_path, parser='pyyaml')
        self.push_pipeline_dict = util.load_yaml_file(self.push_pipeline_yaml_path)

        catalog_docs = util.load_multi_document_yaml_file(self.input_catalog_path)
        self.catalog_dict = catalog_util.build_catalog_index(catalog_docs)

        LOGGER.debug(f"build_config: {json.dumps(self.build_config, indent=4, default=str)}")
        LOGGER.debug(f"patch_dict: {json.dumps(self.patch_dict, indent=4, default=str)}")
        LOGGER.debug(f"catalog_dict: {json.dumps(self.catalog_dict, indent=4, default=str)}")
        LOGGER.info("All yaml files loaded successfully!")

    def process(self) -> None:
        LOGGER.info("")
        LOGGER.info("=============================================================================")
        LOGGER.info("Step 1/4: Generate catalog build args")
        LOGGER.info("=============================================================================")
        self.catalog_build_args = self.generate_catalog_build_args()

        LOGGER.info("")
        LOGGER.info("=============================================================================")
        LOGGER.info("Step 2/4: Patch catalog")
        LOGGER.info("=============================================================================")
        self.patch_catalog()

        LOGGER.info("")
        LOGGER.info("=============================================================================")
        LOGGER.info("Step 3/4: Process push pipeline")
        LOGGER.info("=============================================================================")
        self.is_push_pipeline_updated, self.push_pipeline_dict = util.process_push_pipeline(
            self.push_pipeline_dict, self.push_pipeline_operation
        )

        LOGGER.info("")
        LOGGER.info("=============================================================================")
        LOGGER.info("Step 4/4: Write output files")
        LOGGER.info("=============================================================================")
        self.write_output_files()

    def generate_catalog_build_args(self) -> str:
        """
        Generates catalog_build_args — a KEY=VALUE string containing git URLs and commits
        for the operator bundle and all its components referenced in the bundle.

        Two sources are combined:
          1. bundle_args: the bundle's own git metadata (from --bundle-git-url/--bundle-git-commit CLI args)
          2. bundle_build_args: Remaining components git metadata fetched from bundle_build_args.map
        """
        LOGGER.info("  Using git metadata from bundle image labels:")
        LOGGER.info(f"    bundle_git_url:    {self.bundle_git_url}")
        LOGGER.info(f"    bundle_git_commit: {self.bundle_git_commit}")

        # e.g. "odh-operator-bundle" -> "ODH_OPERATOR_BUNDLE"
        component_prefix = self.bundle_component_name.replace("-", "_").upper()

        # Part 1: operator bundle's own git metadata
        bundle_args = (
            f'{component_prefix}_GIT_URL={self.bundle_git_url}\n'
            f'{component_prefix}_GIT_COMMIT={self.bundle_git_commit}\n'
        )
        LOGGER.debug(f"  bundle_args:\n{bundle_args}")

        # Part 2: remaining components git metadata from bundle_build_args.map
        LOGGER.info("  Fetching remaining git metadata from bundle_build_args.map...")
        bundle_build_args = util.fetch_file_data_from_github(
            git_url=self.bundle_git_url,
            git_commit=self.bundle_git_commit,
            file_path=CONSTANTS.BUNDLE_BUILD_ARGS_PATH
        )
        LOGGER.debug(f"  bundle_build_args:\n{bundle_build_args}")

        # Combine: catalog_build_args = bundle's own metadata + bundle_build_args
        catalog_build_args = bundle_args + bundle_build_args
        LOGGER.info("  Generating catalog_build_args entries...")
        LOGGER.debug(f"  catalog_build_args:\n{catalog_build_args}")
        LOGGER.info("Catalog build args generated successfully!")
        return catalog_build_args

    def patch_catalog(self) -> None:
        """
        Patches the input catalog with the new release's OLM bundle and channel entries.

        Steps:
          1. Extract the olm.bundle document from the single-bundle catalog (SBC)
          2. If the bundle already exists in the catalog, return early (idempotent)
          3. Apply image registry/repo replacements (quay.io -> registry.redhat.io)
          4. Add the bundle to the catalog
          5. Merge/reset olm.package and olm.channels from catalog-patch.yaml
          6. Remove orphan bundles (bundles not referenced by any channel)
          7. Purge explicitly named bundles (optional, via --purge-bundles)

        Steps 3-7 are skipped if the bundle already exists (step 2).

        Modifies self.catalog_dict in-place.
        """
        LOGGER.info(f"  Input catalog:          {self.input_catalog_path}")
        LOGGER.info(f"  Single bundle catalog:  {self.single_bundle_catalog_path}")
        LOGGER.info(f"  Output catalog:         {self.output_catalog_path}")

        # Step 1: Extract the olm.bundle document from the SBC
        sbc_docs = util.load_multi_document_yaml_file(self.single_bundle_catalog_path)
        olm_bundle = catalog_util.extract_document_by_schema(sbc_docs, CONSTANTS.OLM_BUNDLE_SCHEMA)
        if olm_bundle is None:
            LOGGER.error(f"No olm.bundle found in {self.single_bundle_catalog_path}")
            sys.exit(1)
        bundle_name = olm_bundle['name']
        LOGGER.info(f"  Bundle from SBC: {bundle_name}")

        # Step 2: Check if this bundle already exists. If it does, skip remaining steps.
        if bundle_name in self.catalog_dict[CONSTANTS.OLM_BUNDLE_SCHEMA]:
            LOGGER.warning(f"  Bundle {bundle_name} already exists in catalog — SKIPPING PATCH.")
            return

        # Step 3: Apply registry/repo replacement to the bundle image
        LOGGER.info("  Applying registry and repo replacements for the bundle image...")
        olm_bundle = self._apply_replacements(olm_bundle)

        # Step 4: Add the bundle to the catalog
        LOGGER.info(f"  Adding bundle: {bundle_name} to the output catalog...")
        self.catalog_dict[CONSTANTS.OLM_BUNDLE_SCHEMA][bundle_name] = olm_bundle

        # Step 5: Patch olm.package and olm.channels from catalog-patch.yaml
        catalog_util.patch_olm_package(self.catalog_dict, self.patch_dict)
        catalog_util.patch_olm_channels(self.catalog_dict, self.patch_dict)

        # Step 6: Remove orphan bundles — bundles not referenced by any channel entry
        # e.g. old EA version replaced by new one in beta channel after a RESET
        LOGGER.info("  Purging orphan bundles...")
        catalog_util.purge_orphan_bundles(self.catalog_dict)

        # Step 7 (optional): Purge explicitly named bundles via --purge-bundles
        # Only removes olm.bundle entries — does NOT remove references from channel entries
        if self.purge_bundles:
            LOGGER.info(f"  Purging explicitly named bundles: {self.purge_bundles}")
            catalog_util.purge_bundles(self.catalog_dict, self.purge_bundles.split(","))

        LOGGER.info("Catalog patched successfully.")

    def _apply_replacements(self, olm_bundle: Dict) -> Dict:
        """
        Replaces dev registry/repo paths with production registry/repo paths.
        Targets only the bundle image in two places:

          1. The top-level olm_bundle['image'] — from the semver template
          2. The matching relatedImages entry — added by opm for disconnected mirroring
             (identified by matching the original bundle image value)

        The remaining relatedImages are not touched as they come from the bundle's CSV where
        the bundle-processor has already applied the replacements while processing the bundle.

        Background:
            When the SBC (single-bundle catalog) is generated by opm:

                opm alpha render-template semver -o yaml fbc-semver-template.yaml > sbc.yaml

            opm pulls the bundle image from the semver template, extracts its
            metadata, and produces an olm.bundle document with:
              - An 'image' field pointing to the bundle image (from the template)
              - A 'relatedImages' list containing ALL images the operator needs for disconnected mirroring:
                  * The bundle image itself — added automatically by opm with an empty name
                  * All operand images — extracted from the bundle's CSV

            The resulting olm.bundle looks like:

                image: quay.io/rhoai/odh-operator-bundle@sha256:...     <-- opm adds this (needs replacement)
                relatedImages:
                  - name: ""                                             <-- opm adds this (needs replacement)
                    image: quay.io/rhoai/odh-operator-bundle@sha256:...
                  - name: operator_image                                 <-- from CSV (does not need replacement)
                    image: registry.redhat.io/rhoai/odh-rhel9-operator@sha256:...
                  - name: dashboard_image                                <-- from CSV (does not need replacement)
                    image: registry.redhat.io/rhoai/odh-dashboard-rhel9@sha256:...
        """
        for replacement in self.build_config['config']['replacements']:
            source_registry = replacement['registry']
            for source_repo, target_repo in replacement['repo_mappings'].items():
                old_prefix = f'{source_registry}/{source_repo}@'
                new_prefix = f'{CONSTANTS.PRODUCTION_REGISTRY}/{target_repo}@'

                if old_prefix in olm_bundle['image']:
                    original_image = olm_bundle['image']
                    olm_bundle['image'] = original_image.replace(old_prefix, new_prefix)
                    LOGGER.info(f"    image: {original_image} -> {olm_bundle['image']}")

                    # Replace the matching entry in relatedImages (same image as top-level)
                    for entry in olm_bundle.get('relatedImages', []):
                        if entry.get('image', '') == original_image:
                            entry['image'] = entry['image'].replace(old_prefix, new_prefix)
                            LOGGER.info(f"    relatedImages: {original_image} -> {entry['image']}")
                            break
                    break

        return olm_bundle

    def write_output_files(self) -> None:
        """
        Writes all modified files to disk:
          - Patched catalog YAML
          - catalog_build_args.map
          - Push pipeline YAML
        """
        os.makedirs(os.path.dirname(self.output_catalog_path), exist_ok=True)

        catalog_util.write_catalog_yaml(self.catalog_dict, self.output_catalog_path)

        util.write_file(self.catalog_build_args, self.catalog_build_args_file_path)

        if self.is_push_pipeline_updated:
            util.write_yaml_file(self.push_pipeline_dict, self.push_pipeline_yaml_path)

        LOGGER.info("  Output files written successfully!")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='FBC Processor: patches a single OLM catalog for one RHOAI release.'
    )
    parser.add_argument('-v', '--rhoai-version', required=True,
                        help='The version of Openshift-AI being processed (e.g. rhoai-3.5-ea.1)',
                        dest='rhoai_version')
    parser.add_argument('-t', '--build-type', required=True,
                        help='Build type: "ci" or "nightly"', dest='build_type')
    parser.add_argument('-b', '--build-config-path', required=True,
                        help='Path of the build-config.yaml', dest='build_config_path')
    parser.add_argument('-p', '--patch-yaml-path', required=True,
                        help='Path of the catalog-patch.yaml from the release branch',
                        dest='patch_yaml_path')
    parser.add_argument('-s', '--single-bundle-catalog-path', required=True,
                        help='Path of the single-bundle catalog generated by opm',
                        dest='single_bundle_catalog_path')
    parser.add_argument('-c', '--input-catalog-path', required=True,
                        help='Path of the input catalog (PCC or previously-patched)',
                        dest='input_catalog_path')
    parser.add_argument('-o', '--output-catalog-path', required=True,
                        help='Path to write the patched catalog',
                        dest='output_catalog_path')
    parser.add_argument('--bundle-git-url', required=True,
                        help='Git URL from bundle image labels (resolved by skopeo in shell)',
                        dest='bundle_git_url')
    parser.add_argument('--bundle-git-commit', required=True,
                        help='Git commit from bundle image labels (resolved by skopeo in shell)',
                        dest='bundle_git_commit')
    parser.add_argument('--catalog-build-args-file-path', required=True,
                        help='Path to write catalog_build_args.map',
                        dest='catalog_build_args_file_path')
    parser.add_argument('-y', '--push-pipeline-yaml-path', required=True,
                        help='Path of the Tekton push pipeline YAML',
                        dest='push_pipeline_yaml_path')
    parser.add_argument('-x', '--push-pipeline-operation', required=True,
                        help='Push pipeline operation: "enable" or "disable"',
                        dest='push_pipeline_operation')
    parser.add_argument('--purge-bundles', required=False, default='',
                        help='Comma-separated olm.bundle names to delete from the catalog '
                             'after patching. Only removes the bundle entries — does NOT '
                             'remove references from channel entries. Ensure corresponding '
                             'channel entries are also updated to avoid dangling references.',
                        dest='purge_bundles')

    args = parser.parse_args()

    processor = fbc_processor(
        rhoai_version=args.rhoai_version,
        build_type=args.build_type,
        build_config_path=args.build_config_path,
        patch_yaml_path=args.patch_yaml_path,
        single_bundle_catalog_path=args.single_bundle_catalog_path,
        input_catalog_path=args.input_catalog_path,
        output_catalog_path=args.output_catalog_path,
        bundle_git_url=args.bundle_git_url,
        bundle_git_commit=args.bundle_git_commit,
        catalog_build_args_file_path=args.catalog_build_args_file_path,
        push_pipeline_yaml_path=args.push_pipeline_yaml_path,
        push_pipeline_operation=args.push_pipeline_operation,
        purge_bundles=args.purge_bundles
    )
    processor.process()
